### ISSUE TITLE
overview

### ISSUE THREAD

**Issue by tuki0918** [tuki0918/laravel-document-switcher#1]
Ref: https://github.com/tuki0918/Archives-laravel-document-switcher

Refactoring to TypeScript, Redux

#### ToDo
+ [x] Re-implement (Refactoring)
+ [x] Flux to Redux
+ [x] generate redux store  module
+ [ ] Flow or TypeScript (First: test)
+ [x] README.md
+ [ ] ~compile environment (with Docker)~
+ [ ] testing (jest FW)
    + [x] compoment
    + [x] reducer
    + [ ] lib (mock)
+ [x] chrome web store
+ [x] CI, badge
+ [ ] eslint
+ [x] npm module classnames
